---
title: "Script_to_format_Fish_data_for_NCRA_Analysis"
author: "Swaleh Aboud"
date: "2025-04-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

knitr::opts_chunk$set(warning = FALSE, message = FALSE)

```


# Calling Required Packages

```{r}
# Callning package
library(dplyr)
library(forcats)
library(magrittr)
library(readxl)


```


# Import old RLE files

```{r}

# Import data file and select for Tanzania
Fish_NCRA <- read_excel("../../../data_raw/WIO_GCRMN_fish_data_all_levels_Feb_2020.xlsx", 
    sheet = "WIO_GCRMN_fish_data_all_levels_")

Fish_NCRA<- Fish_NCRA[Fish_NCRA$Country =="Comoros", ] # filter for Comoros

Fish_NCRA2<- Fish_NCRA[Fish_NCRA$level1_code=="serra" | Fish_NCRA$level1_code=="scari",]

# Import Geofile and select for Tanzania
Geo_file<-read.csv(file = "../../../../Ecological-Research-Data-Analysis/1. Data processing/Template files/Overall_Geo-file_Updated.csv" ,header = TRUE)

Geo_file<- Geo_file[Geo_file$Country =="Comoros", ] 


```


# Standardising Sites names

```{r}

# Checked for unmatched site names
h<-match(Fish_NCRA2$Station,Geo_file$Proposed_Station,nomatch = 0)
unique(Fish_NCRA2$Station[h==0])

Fish_NCRA2$Station_corrected<-Fish_NCRA2$Station

# Make corrections
Fish_NCRA2%<>%
  mutate(Station_corrected = Station_corrected %>% factor() %>%
           fct_recode(`Bwana_Iddi` = "Bwanaidi",
                      `MW_D_P_SC13` = "Mereni",
                      `MW_D_P_SC14` = "Mirereni",
                      `Sambia_West` = "Sambia_Reserve",
                       Chin_04 = "Chindini",
                       Barakani = "Itsandra", 
                       Moindzaza = "Moindzzaza",
                       Shiroroni = "Shomoni"
                      ))

Fish_NCRA2 <- Fish_NCRA2 %>%
  mutate(
    Station_corrected = case_when(
      Site_id == "Comoros,Anjouan,A"         ~ "Mtsaka",
      Site_id == "Comoros,Grand_Comore,A"    ~ "GC_A_P_SC05",
      Site_id == "Comoros,Moheli,A"          ~ "MW_A_P_SC19",
      Site_id == "Comoros,Anjouan,B"         ~ "Habwanajibou_01",
      Site_id == "Comoros,Grand_Comore,B"    ~ "MW_E_P_SC10",
      Site_id %in% c("Comoros,Moheli,B_-_N", "Comoros,Moheli,B_-_S") ~ "MW_B_P_SC16",
      Site_id == "Comoros,Moheli,D"          ~ "Mea",
      Site_id == "Comoros,Moheli,E"          ~ "Ferenga",
      TRUE                                    ~ Station_corrected  # Keep existing if no match
    )
  )

# check again
# Checked for unmatched site names
h<-match(Fish_NCRA2$Station_corrected,Geo_file$Proposed_Station,nomatch = 0)
unique(Fish_NCRA2$Station_corrected[h==0])


# Add other columns
Fish_NCRA2$site_corrected<-Geo_file$Proposed_Site[match(Fish_NCRA2$Station_corrected, Geo_file$Proposed_Station)]
Fish_NCRA2$Location<-Geo_file$Proposed_Location[match(Fish_NCRA2$Station_corrected, Geo_file$Proposed_Station)]
Fish_NCRA2$Sector<-Geo_file$Proposed_Sector[match(Fish_NCRA2$Station_corrected, Geo_file$Proposed_Station)]
Fish_NCRA2$Management_level<-Geo_file$Management_level[match(Fish_NCRA2$Station_corrected, Geo_file$Proposed_Station)]
Fish_NCRA2$Latitude<-Geo_file$Latitude_old[match(Fish_NCRA2$Station_corrected, Geo_file$Proposed_Station)]
Fish_NCRA2$Longitude<-Geo_file$Longitude_old[match(Fish_NCRA2$Station_corrected, Geo_file$Proposed_Station)]

# Fills other blanks fields
#Sector
Fish_NCRA2 <- Fish_NCRA2 %>%
  mutate(
    Sector = case_when(
      Station_corrected %in% c("Shom1") ~ "Grand Comore",
      Station_corrected %in% c("Point Ouani", "Djirani") ~ "Moheli Island",
      TRUE ~ Sector  # keep existing value if not matched
    )
  )

# Site
Fish_NCRA2 <- Fish_NCRA2 %>%
  mutate(
    site_corrected = case_when(
      Station_corrected %in% c("Shom1") ~ "Shomoni",
      Station_corrected %in% c("Djirani") ~ "Djirani",
      Station_corrected %in% c("Point Ouani") ~ "Point Ouani",
      TRUE ~ site_corrected  # keep existing value if not matched
    )
  )


# Management level
Fish_NCRA2 <- Fish_NCRA2 %>%
  mutate(
    Management_level = case_when(
      Station_corrected %in% c("Shom1","Djirani","Point Ouani") ~ "Open access",
      TRUE ~ Management_level  # keep existing value if not matched
    )
  )


# Latitude
Fish_NCRA2 <- Fish_NCRA2 %>%
  mutate(
    Latitude = case_when(
      Station_corrected %in% c("Shom1") ~ "-11.64467",
      Station_corrected %in% c("Djirani") ~ "-12.28323",
      Station_corrected %in% c("Point Ouani") ~ "-12.24682",
      TRUE ~ Latitude  # keep existing value if not matched
    )
  )

# Longitude
Fish_NCRA2 <- Fish_NCRA2 %>%
  mutate(
    Longitude = case_when(
      Station_corrected %in% c("Shom1") ~ 43.395,
      Station_corrected %in% c("Djirani") ~ 43.6221,
      Station_corrected %in% c("Point Ouani") ~ 43.65845,
      TRUE ~ Longitude  # keep existing value if not matched
    )
  )


# Add Sub-national
unique(Fish_NCRA2$Location)
Fish_NCRA2$`sub-national`<- Fish_NCRA2$Sector

# Add Eco-region
Fish_NCRA2$Eco_region<-Fish_NCRA2$`sub-national`

Fish_NCRA2$Organization <- "CORDIO"

# Starndise family names
Fish_NCRA2%<>%
  mutate(fish_name = fish_name %>% factor() %>%
           fct_recode(`Scarinae` = "Scaridae",
                      `Epinephelidae`     = "Serranidae"))

# Management
Fish_NCRA2%<>%
  mutate(Management_level = Management_level %>% factor() %>%
           fct_recode(`Partially Restricted` = "Partially restricted"))



```


# Format current CORDIO Data 2022-2024

```{r}

Fish_current <- read.csv("../../../data_raw/Fish_site_summary_families_all-years.csv")

# Check Site naming
# Checked for unmatched site names
m<-match(Fish_current$Site,Geo_file$Proposed_Site,nomatch = 0)
unique(Fish_current$Site[m==0])

# make any corrections
# Fish_current%<>%
#   mutate(Site = Site %>% factor() %>%
#            fct_recode(`Memboimboini` = "Memboiboini",
#                       `Mitsamiuli`     = "Mitsamiouli"))

# Add other columns
Fish_current$Sector<-Geo_file$Proposed_Sector[match(Fish_current$Site, Geo_file$Proposed_Site)]
Fish_current$`sub-national`<- Fish_current$Sector
Fish_current$Eco_region<-Fish_current$`sub-national`

# Select for Groupers and Parrotfish
Fish_current<- Fish_current[Fish_current$Family=="Epinephelidae" | Fish_current$Family=="Scarinae",]

Fish_current$Organization <- "CORDIO"



```


# Format current DAHARI Data 2022-2024
```{r}

Fish_DAHARI <- read.csv("../../../data_raw/Fishabundance_Site_families_mean_DAHARI.csv")


# Checked for unmatched site names
k<-match(Fish_DAHARI$Site,Geo_file$Proposed_Site,nomatch = 0)
unique(Fish_DAHARI$Site[k==0])

# Add other columns
Fish_DAHARI$Sector<-Geo_file$Proposed_Sector[match(Fish_DAHARI$Site, Geo_file$Proposed_Site)]
Fish_DAHARI$`sub-national`<- Fish_DAHARI$Sector
Fish_DAHARI$Eco_region<-Fish_DAHARI$`sub-national`


# Select for Groupers and Parrotfish
Fish_DAHARI <- Fish_DAHARI[!is.na(Fish_DAHARI$Family) & 
                            Fish_DAHARI$Family %in% c("Epinephelidae", "Scarinae"), ]

Fish_DAHARI$Organization <- "DAHARI"

# Management
Fish_DAHARI%<>%
  mutate(Management_level = Management_level %>% factor() %>%
           fct_recode(`Partially Restricted` = "Partially restricted"))


```

# Format Reference site dataset

```{r}

# Chagos
chagos_data <- read_excel("../../../data_raw/Grouper parrotfish metrics_summaries _threshold_simplified_KO_MS16jan.xlsx", 
    sheet = "Chagos")

chagos_data <- chagos_data[-c(1:18, 34:36),]
chagos_data <- chagos_data[, c(1,9,10,11,12)]


# Restructure the dataset
# Start from row 3 (actual data)
chagos_cleaned <- chagos_data[3:nrow(chagos_data), ]

# Set column names using row 2
colnames(chagos_cleaned) <- chagos_data[2, ]

# Rename the first column
colnames(chagos_cleaned)[1] <- "Station_corrected"

# Ensure all column names are unique
names(chagos_cleaned) <- make.names(names(chagos_cleaned), unique = TRUE)

# Restructure to long format
chagos_long <- chagos_cleaned %>%
  dplyr::mutate(
    Scarinae_density = as.numeric(Density),
    Scarinae_biomass = as.numeric(Biomass),
    Epinephelidae_density = as.numeric(Density.1),
    Epinephelidae_biomass = as.numeric(Biomass.1)
  ) %>%
  dplyr::select(
    Station_corrected,
    Scarinae_density, Scarinae_biomass,
    Epinephelidae_density, Epinephelidae_biomass
  ) %>%
  tidyr::pivot_longer(
    cols = -Station_corrected,
    names_to = c("family", ".value"),
    names_sep = "_"
  )

# Rename the other column
colnames(chagos_long)[3] <- "density.ind.ha."
colnames(chagos_long)[4] <- "biomass.kg.ha."

# Add Location
chagos_long$Location <- "Chagos Islands"



# Gloriuse
# Chagos
gloriuse_data <- read_excel("../../../data_raw/Grouper parrotfish metrics_summaries _threshold_simplified_KO_MS16jan.xlsx", 
    sheet = "Glorieuses")

gloriuse_data <- gloriuse_data[c(10,11,15, 16),] #select rows
gloriuse_data <- gloriuse_data[-c(14:17)] #select rows


# Restructure

# Keep only the data rows from row 3 onward
gloriuse_clean <- gloriuse_data[3:nrow(gloriuse_data), ]
names(gloriuse_clean)[1] <- "family"

# Extract station names from the second row, skipping first column
station_names <- gloriuse_data[2, -1] |> unlist() |> as.character()

# Identify all station pairs (density + biomass)
n_pairs <- length(station_names) / 2  # since each station has 2 columns

# Initialize list
long_data_list <- list()

for (i in seq_len(n_pairs)) {
  # Identify the column positions for this station's density and biomass
  dens_col <- 2 * i      # even column
  bio_col <- 2 * i + 1   # next column (odd)
  
  station <- station_names[dens_col - 1]  # get station name (e.g., "Glo15.1")
  
  df <- gloriuse_clean %>%
    dplyr::select(family, 
                  density = !!sym(names(gloriuse_clean)[dens_col]), 
                  biomass = !!sym(names(gloriuse_clean)[bio_col])) %>%
    dplyr::mutate(
      Station_corrected = station
    )
  
  long_data_list[[i]] <- df
}


# Combine and clean
gloriuse_final <- dplyr::bind_rows(long_data_list) %>%
  dplyr::mutate(
    Mean_density = as.numeric(density),
    Mean_biomass = as.numeric(biomass)
  ) %>%
  dplyr::select(Station_corrected, family, Mean_density, Mean_biomass)

# Rename the other column
colnames(gloriuse_final)[3] <- "density.ind.ha."
colnames(gloriuse_final)[4] <- "biomass.kg.ha."

# Add Location
gloriuse_final$Location <- "Glorieuses Islands"


# Bind the 2
Ref_data<- rbind(gloriuse_final, chagos_long)

# Rename family names
Ref_data <- Ref_data %>%
  mutate(family = case_when(
    family == "Scaridae"      ~  "Scarinae",
    family == "Serranidae"  ~  "Epinephelidae",
    TRUE                      ~ family
  ))


```


# Merge the four Dataset
 # Format and saving output file

```{r}

# Check columns names on both files
names(Fish_NCRA2)
names(Fish_current)
names(Fish_DAHARI)
names(Ref_data)

# Format for issues


# Format for Issues
# old dataset
names(Fish_NCRA2)[names(Fish_NCRA2)=="fish_name"]<-"family"

#New dataset
# CORDIO current
Fish_current$Station <- Fish_current$Site
Fish_current$Station_corrected <- Fish_current$Site
Fish_current$site_corrected <- Fish_current$Site
names(Fish_current)[names(Fish_current)=="Family"]<-"family"
names(Fish_current)[names(Fish_current)=="Mean_density"]<-"density.ind.ha."
names(Fish_current)[names(Fish_current)=="sd_d"]<-"sd_density"
names(Fish_current)[names(Fish_current)=="Mean_biomass"]<-"biomass.kg.ha."
names(Fish_current)[names(Fish_current)=="sd_b"]<-"sd_biomass"

# DAHARI dataset
Fish_DAHARI$Station <- Fish_DAHARI$Site
Fish_DAHARI$Station_corrected <- Fish_DAHARI$Site
Fish_DAHARI$site_corrected <- Fish_DAHARI$Site
names(Fish_DAHARI)[names(Fish_DAHARI)=="Family"]<-"family"
names(Fish_DAHARI)[names(Fish_DAHARI)=="Mean_density"]<-"density.ind.ha."
names(Fish_DAHARI)[names(Fish_DAHARI)=="sd_d"]<-"sd_density"
names(Fish_DAHARI)[names(Fish_DAHARI)=="Mean_biomass"]<-"biomass.kg.ha."
names(Fish_DAHARI)[names(Fish_DAHARI)=="sd_b"]<-"sd_biomass"


# Reference dataset
Ref_data$Date <- ""
Ref_data$Year <- ""
Ref_data$Location <- ""
Ref_data$Management_level <- "Reference"
Ref_data$Latitude <- ""
Ref_data$Longitude <- ""
Ref_data$number_transect <- ""
Ref_data$sd_biomass <- ""
Ref_data$se_b <- ""
Ref_data$sd_density <- ""
Ref_data$se_d <- ""
Ref_data$Sector <- "Reference"
Ref_data$Organization <- ""
Ref_data$site_corrected <- Ref_data$Station_corrected
Ref_data$Country <- "Reference"
Ref_data$Site <- Ref_data$Station_corrected
Ref_data$site_corrected <- ""
Ref_data$Station <- Ref_data$Station_corrected
Ref_data$Organization <- "CORDIO"
Ref_data$Eco_region <- "Reference"
Ref_data$`sub-national` <- "Reference"

# Order columns
# Old
Fish_NCRA3<-Fish_NCRA2[,c("Country","sub-national","Eco_region",  "Year", "Management_level", "Sector", "Location","Site", "site_corrected", "Station", "Station_corrected","family", "density.ind.ha.","sd_density","biomass.kg.ha.","sd_biomass","Organization")]

#New
Fish_current2<-Fish_current[,c("Country","sub-national","Eco_region",  "Year", "Management_level", "Sector", "Location","Site", "site_corrected", "Station", "Station_corrected","family", "density.ind.ha.","sd_density","biomass.kg.ha.","sd_biomass","Organization")]

#DAHARI
Fish_DAHARI2<-Fish_DAHARI[,c("Country","sub-national","Eco_region",  "Year", "Management_level", "Sector", "Location","Site", "site_corrected", "Station", "Station_corrected","family", "density.ind.ha.","sd_density","biomass.kg.ha.","sd_biomass","Organization")]

#Reference
Ref_data2<-Ref_data[,c("Country","sub-national","Eco_region",  "Year", "Management_level", "Sector", "Location","Site", "site_corrected", "Station", "Station_corrected","family", "density.ind.ha.","sd_density","biomass.kg.ha.","sd_biomass","Organization")]


# Merge four files
Fish_NCRA_complete <- rbind(Fish_NCRA3, Fish_current2, Fish_DAHARI2, Ref_data2)

# Rename sub-National and Ecoregion
Fish_NCRA_complete %<>%
  mutate(
    `sub-national` = recode_factor(`sub-national`,
                                   "Moheli island" = "Mwali",
                                   "Moheli Island" = "Mwali",
                                   "Grand Comore" = "Ngazidja",
                                   "Anjouan Island" = "Ndzuani"))

Fish_NCRA_complete %<>%
  mutate(
    Eco_region = recode_factor(Eco_region,
                                "Moheli island" = "Mwali",
                                "Moheli Island" = "Mwali",
                                "Grand Comore" = "Ngazidja",
                                "Anjouan Island" = "Ndzuani")
  )


# Order by years
Fish_NCRA_complete <- Fish_NCRA_complete %>%
  arrange(Year, Site)

# Round vaues to 2 decimals
Fish_NCRA_complete$sd_biomass <- as.numeric(as.character(Fish_NCRA_complete$sd_biomass))

Fish_NCRA_complete$sd_density <- as.numeric(as.character(Fish_NCRA_complete$sd_density))

Fish_NCRA_complete <- Fish_NCRA_complete %>%
  mutate(
    `density.ind.ha.` = round(`density.ind.ha.`, 2),
    sd_density = round(sd_density, 2),
    `biomass.kg.ha.` = round(`biomass.kg.ha.`, 2),
    sd_biomass = round(sd_biomass, 2)
  )

# Save output file

save(Fish_NCRA_complete, file = "../../../data_intermediate/Fish_NCRA_dataset_2025.RDA")

write.csv(Fish_NCRA_complete,"../../../data_intermediate/Fish_NCRA_dataset_2025.csv",row.names = F)


```

# Initial value file

```{r}

# Filter for initia values
initial_values <- Fish_NCRA_complete %>%
  dplyr::filter(
    Eco_region == "Reference" |
      (Eco_region == "Mwali" & Year == 2018)
  )

# Calculate baseline values

# Group by family and compute overall mean and SD
baseline_stats <- initial_values %>%
  dplyr::group_by(family) %>%
  dplyr::summarise(
    baseline_mean = mean(biomass.kg.ha., na.rm = TRUE),
    baseline_sd = sd(biomass.kg.ha., na.rm = TRUE),
    .groups = "drop"
  )

# Define ecoregions to assign
ecoregions <- c("Moheli Island", "Grand Comore Island", "Anjoun Island", "National")

# Step 3: Expand and assign ecoregions to each family row
baseline_comoros <- tidyr::expand_grid(
  eco_rgn = ecoregions,
  baseline_stats
) %>%
  dplyr::select(eco_rgn, fish = family, baseline_mean, baseline_sd)


# Save file
save(baseline_comoros, file = "../../../data_intermediate/Criteria_D_fish_baseline_ref.rda")


```

# Current values file

```{r}

# Select values from 2016
current_values <- Fish_NCRA_complete %>%
  dplyr::filter(Year >= "2016")

# Create site_id
current_values <- current_values %>%
  mutate(
    site_id = str_c(Country, Eco_region, Sector, site_corrected, sep = "_")
  )

# Get first and recent year per site_id
year_info <- current_values %>%
  group_by(site_id) %>%
  summarise(
    first_year = min(as.numeric(Year), na.rm = TRUE),
    recent_year = max(as.numeric(Year), na.rm = TRUE),
    .groups = "drop"
  )

# Compute current and recent biomass per site_id and eco_region
biomass_info <- current_values %>%
  group_by(site_id, Eco_region, family, Year) %>%
  summarise(
    avg_biom = mean(as.numeric(biomass.kg.ha.), na.rm = TRUE),
    .groups = "drop"
  )

# Get average over all years (current_biom)
current_biom <- biomass_info %>%
  group_by(site_id, Eco_region, family) %>%
  summarise(current_biom = mean(avg_biom, na.rm = TRUE), .groups = "drop")

# Get most recent year (recent_biom)
recent_biom <- biomass_info %>%
  inner_join(year_info, by = "site_id") %>%
  filter(Year == recent_year) %>%
  dplyr::select(site_id, recent_biom = avg_biom, family)

# Prepare threshold data
thresholds <- baseline_comoros %>%
  mutate(
    threshold_ref_max = case_when(
      fish == "Scarinae" ~ baseline_mean * 0.1,
      fish == "Epinephelidae" ~ baseline_mean * 0.2,
      TRUE ~ NA_real_
    )
  ) %>%
  dplyr::select(fish, threshold_ref_max)

fish_current_values <- current_values %>%
  dplyr::select(site_id, Eco_region, family) %>%
  distinct() %>%  # keep only one row per site_id/ecoregion/fish
  left_join(current_biom, by = c("site_id", "Eco_region", "family")) %>%
  left_join(recent_biom, by = c("site_id", "family")) %>%
  left_join(year_info, by = "site_id") %>%
  rename(eco_rgn = Eco_region, fish = family) %>%
  left_join(thresholds, by = "fish") %>%
  mutate(
    threshold_ref_min = NA,
    fish = recode(fish,
                  "Epinephelidae" = "Groupers",
                  "Scarinae" = "Parrotfish")
  ) %>%
  dplyr::select(eco_rgn, site_id, first_year, recent_year,
         current_biom, recent_biom,
         threshold_ref_max, threshold_ref_min, fish) %>%
  distinct()  # <- this line ensures final output has no duplicates


# Save file
save(fish_current_values, file = "../../../data_intermediate/Criteria_D_fish_data_table.rda")


```









